version: '3'
services:
  gif-generator:
    build: .
    volumes:
      - ./:/app
      - ./output:/app/output
    working_dir: /app
    # For Apple Silicon Macs, the following is needed for Metal acceleration
    platform: linux/arm64
    environment:
      - PYTORCH_ENABLE_MPS_FALLBACK=1
